package com.ashutosh.musicsync.domain.model.currentSong

import com.google.gson.annotations.SerializedName

data class CurrentSong(
    val id: String?,
    val type: String?,
    val song: String?,
    val album: String?,
    val year: String?,
    val music: String?,
    val music_id: String?,
    val primary_artists: String?,
    val primary_artists_id: String?,
    val featured_artists: String?,
    val featured_artists_id: String?,
    val singers: String?,
    val starring: String?,
    val image: String?,
    val label: String?,
    val albumid: String?,
    val language: String?,
    val origin: String?,
    val play_count: Long?,
    val is_drm: Int?,
    val copyright_text: String?,
    @SerializedName("320kbps")
    val is320kbps: String?,
    val is_dolby_content: Boolean?,
    val explicit_content: Int?,
    val has_lyrics: String?,
    val lyrics_snippet: String?,
    val encrypted_drm_media_url: String?,
    val encrypted_media_url: String?,
    val encrypted_media_path: String?,
    val media_preview_url: String?,
    val perma_url: String?,
    val album_url: String?,
    val duration: String?,
    val rights: Rights?,
    val webp: Boolean?,
    val cache_state: String?,
    val starred: String?,
    val artistMap: Map<String, String>?,
    val release_date: String?,
    val vcode: String?,
    val vlink: String?,
    val triller_available: Boolean?,
    val label_url: String?,
    val label_id: String?
)
